name: Build and Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from your repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.1' # Use a stable Node.js version
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the project
    - name: Build Project
      run: npm run build

    # Step 5: Configure AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} # Change to your S3 bucket's region

    # Step 6: Sync build output to S3
    - name: Deploy to S3
      run: |
        aws s3 sync ./dist s3://arnisportfolio --delete
